### ISSUE TITLE
No Module 'array'

### ISSUE THREAD

**Issue by DuckHawk123** [benevpi/pico_python_ws2812b#11]
I'm getting an error indicating that I need a module 'array' to import.

Where do I locate the appropriate 'array' module to load on the pico?

**Comment by aallan** [comment]
Hey there! The RP2040 MicroPython port has now been merged upstream to the main MicroPython repo, see micropython/micropython#6791, and there is an issue for this problem, micropython/micropython#6837, which has been resolved. 

You'll need update your version of MicroPython to the new nightly build, the pre-built UF2 with the fix in it that solves this issue can be found at https://www.raspberrypi.org/documentation/pico/getting-started/.

**Comment by The-Spirit** [comment]
Had the same issue, and I can confirm that the above solution solves the problem.
