### ISSUE TITLE
ws2812b

### ISSUE THREAD

**Issue by ebolisa** [benevpi/pico_python_ws2812b#12]
Hi, which array lib is the ws2812b lib using?
Thank you.

**Comment by benevpi** [comment]
If you're getting an import error on array then you need to grab the latest
firmware from
https://www.raspberrypi.org/documentation/pico/getting-started/

A duff version was temporarily online a little while ago that threw an
import error on array when you tried to use PIO.

Ben

**Comment by ebolisa** [comment]
Thank you.
