### ISSUE TITLE
No output on GPIO when using this lib, but okay when using a simple test program

### ISSUE THREAD

**Issue by root42** [benevpi/pico_python_ws2812b#15]
I have tried your library, but there is no output (checked with a scope) on the GPIO pin, however all is fine when using this test program:

```
from machine import Pin
from rp2 import PIO, StateMachine, asm_pio

@asm_pio(set_init=PIO.OUT_LOW)
def square():
    wrap_target()
    set(pins, 1)
    set(pins, 0)
    wrap()
    
sm = rp2.StateMachine(0, square, freq=2000, set_base=Pin(2))

sm.active(1)
```

The test program for your library looks like this:

```
import ws2812b
import time

i = 0
di = 1
pixels = ws2812b.ws2812b(64,0,2)
while True:
    if i > 20 or i < 0:
        di = -di
    pixels.fill(i,i,i)
    time.sleep(0.05)
    i = i + di
```

Attaching a 8x8 LED array leads to nothing, probing GPIO2 with my scope also shows nothing, in contrast to the first test program. I had a look at the library code, but it looked fine to me, however I am new to the Pico, so can't really say much about it.

**Comment by blaz-r** [comment]
You will need to use pixels.show() whenever you send new data to strip. Show functions is the one that actually sends data out.

**Comment by root42** [comment]
I feel quite stupid now. Ok, that did help. Now the last 6 LEDs in the matrix show garbage. Not sure if they are broken or if this is the RGB vs RGBW issue.

The signal on the scope looks great! So that's not the problem it seems. I will try other values than shades of white to see if it is an RGBW problem.

EDIT: one of the LEDs is flaky. That's why the last few showed garbage. Thanks again and sorry for my ignorance!

**Comment by blaz-r** [comment]
This library works with RGB (actually GRB). For RGBW this one won't do. I'm not sure if it's appropriate of me to say that here, but you can find library that works with RGBW and all orders of bits (GRBW...) on my profile. Do mind that my version uses tuples: (r, g, b, w). 
Edit: This one might actually work, but it all depends on how your led-strip works. Usually RGBW doesn't work the same.

**Comment by benevpi** [comment]
Absolutely it's appropriate. No point in being prudish, you've done a bunch of work to make this work with more hardware, and that's going to benefit a bunch more people. I think the change to accept tuples of colours is the right call as well. 

I'll have a play around with it, but it it works as it looks like it should, I'll retire my library and point people to yours.

The link for blaz-r's library is: https://github.com/blaz-r/pi_pico_neopixel.
